<?php
echo "\e[33mMasukan Nomor Resi : \e[39m";
$resi1 = trim(fgets(STDIN));
$awb1 = substr($resi1, 0, -4);
$res1 = $awb1."****";
sleep(3);
echo "\n";
echo "\e[32mSedang Check Resi : $res1\e[39m".PHP_EOL;
$jne1 = file_get_contents("http://yaelahtih.com/resi/apiv2.php?resi=$resi1&kurir=jne");
$js = json_decode($jne1);
$kurir = $js->Kurir;
$jenislayanan = $js->JenisLayanan;
$pengirim = $js->Pengirim;
$penerima = $js->Penerima;
$kotaasal = $js->KotaAsal;
$tujuan = $js->Tujuan;
$totalongkir = $js->TotalOngkir;
$paket = $js->Isi;
$statuskirim = $js->StatusKirim;
$tgl = $js->History[0]->Tanggal;
$lokasi = $js->History[0]->Lokasi;
$status = $js->History[0]->Status;
$keterangan = $js->History[0]->Keterangan;
echo "\n";
echo "\e[36mKurir        : \e[39m".$kurir.PHP_EOL;
echo "\e[36mJenisLayanan : \e[39m".$jenislayanan.PHP_EOL;
echo "\e[36mPengirim     : \e[39m".$pengirim.PHP_EOL;
echo "\e[36mPenerima     : \e[39m".$penerima.PHP_EOL;
echo "\e[36mKotaAsal     : \e[39m".$kotaasal.PHP_EOL;
echo "\e[36mTujuan       : \e[39m".$tujuan.PHP_EOL;
echo "\e[36mTotalOngkir  : \e[39m".$totalongkir.PHP_EOL;
echo "\e[36mPaket        : \e[39m".$paket.PHP_EOL;
echo "\e[36mStatusKirim  : \e[39m".$statuskirim.PHP_EOL;
echo "\e[36mTanggal      : \e[39m".$tgl.PHP_EOL;
echo "\e[36mLokasi       : \e[39m".$lokasi.PHP_EOL;
echo "\e[36mStatus       : \e[39m".$status.PHP_EOL;
echo "\e[36mKeterangan   : \e[39m".$keterangan.PHP_EOL;
